name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: lsystems
        environment-file: env.yml
        auto-activate-base: false
    - name: Install package
      run: |
        python -m pip install .
    - name: Test
      run: |
        cd test; python -m unittest
